ISO_FILE = "CoreCustom64-5.2.iso"

Vagrant.configure("2") do |config|
  config.ssh.shell = "sh -l"
  config.ssh.username = "tc"

  # Disable synced folders because guest additions aren't available
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Expose the Docker port
  # config.vm.network "forwarded_port", guest: 4243, host: 4243

  # Attach the ISO
  config.vm.provider :virtualbox do |v|
    v.customize ["modifyvm", :id, "--boot1", "dvd", "--boot2", "disk", "--boot3", "none"]
    # v.customize ["storagectl", :id, "--name", "IDE Controller", "--remove"]
    v.customize [
      "storageattach", :id,
      "--storagectl", "SATA Controller",
      "--port", "1",
      "--device", "0",
      "--type", "dvddrive",
      "--medium", File.expand_path("../#{ISO_FILE}", __FILE__),
    ]
  end

  [:vmware_fusion, :vmware_workstation].each do |vmware|
    config.vm.provider vmware do |v|
      v.vmx["bios.bootOrder"]    = "CDROM,hdd"
      v.vmx["ide1:0.present"]    = "TRUE"
      v.vmx["ide1:0.fileName"]   = File.expand_path("../#{ISO_FILE}", __FILE__)
      v.vmx["ide1:0.deviceType"] = "cdrom-image"
    end
  end
end
