# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "gnue/core64-5.2"

  config.vm.provision :shell, :privileged => false, :inline => <<-PREPARE
    PKGS="mkisofs-tools"

    for pkg in $PKGS; do
      tce-load -wi $pkg
    done

    exit 0
  PREPARE

end
